name: tests on s390x

on:
  push:
  workflow_dispatch:

jobs:
  linux-qemu-s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: ubuntu-core:s390x-focal
        shell: bash
        run: |
          docker run --rm --privileged \
            -v "${{ github.workspace }}:/swiss" \
            multiarch/ubuntu-core:s390x-focal \
            bash -c "
                uname -a &&
                lscpu | grep Endian &&
                apt-get update &&
                apt-get install -y wget &&
                wget -q https://go.dev/dl/go1.23.6.linux-s390x.tar.gz &&
                tar xzf go1.23.6.linux-s390x.tar.gz -C /usr/local &&
                export PATH="$PATH:/usr/local/go/bin" &&
                cd /swiss &&
                go version &&
                go env &&
                go test -v ./... &&
                go test -v -tags swiss_invariants ./...
            "
